import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const directory=path.join(root,'dist');
const input=fs.readFileSync(path.join(directory,'data/catalog.json'),'utf8');
const data=JSON.parse(input);
const requireValue=(condition,message)=>{if(!condition)throw new Error(message)};
const isId=value=>typeof value==='string'&&/^[a-z][a-z0-9-]*$/.test(value);
const https=url=>{const u=new URL(url);requireValue(u.protocol==='https:'&&!u.username&&!u.password,'Unsafe source URL: '+url)};
requireValue(data.schemaVersion===1&&Array.isArray(data.parts)&&Array.isArray(data.examples),'Unsupported catalog format');
requireValue(new Set(data.parts.map(p=>p.id)).size===data.parts.length,'Duplicate part ID');
requireValue(new Set(data.examples.map(e=>e.id)).size===data.examples.length,'Duplicate example ID');
for(const p of data.parts){requireValue(isId(p.id),'Invalid part ID');for(const key of ['name','ja','category','summary','description','use','difference','sourceName','hint','recipe'])requireValue(typeof p[key]==='string'&&p[key].length>0&&!/[<>]/.test(p[key]),'Invalid part text: '+p.id+'.'+key);requireValue(Array.isArray(p.aliases)&&p.aliases.every(a=>typeof a==='string'&&!/[<>]/.test(a)),'Invalid aliases');requireValue(['overlay','navigation','input','information'].includes(p.category),'Unknown category');https(p.source);requireValue(p.definitionSources.length>0,'Missing definition source');for(const s of p.definitionSources){https(s.url);requireValue(/^\d{4}-\d{2}-\d{2}$/.test(s.checkedAt),'Missing source date')}const linked=data.examples.filter(e=>e.partId===p.id);requireValue(linked.length>0,'No examples for '+p.id);requireValue(JSON.stringify([...p.exampleIds].sort())===JSON.stringify(linked.map(e=>e.id).sort()),'Broken example relation: '+p.id);requireValue(linked.some(e=>e.id===p.featuredExampleId),'Broken featured example');}
for(const e of data.examples){requireValue(isId(e.id)&&data.parts.some(p=>p.id===e.partId),'Invalid example relation');for(const key of ['system','title','summary','sourceTitle'])requireValue(typeof e[key]==='string'&&e[key].length>0,'Missing example field '+key);requireValue(Array.isArray(e.features)&&e.features.length>0&&e.features.every(f=>typeof f==='string'),'Missing example features');https(e.url);if(e.componentSourceUrl)https(e.componentSourceUrl);requireValue(/^\d{4}-\d{2}-\d{2}$/.test(e.checkedAt),'Invalid check date');requireValue(e.verification.documentReviewed===true,'Unreviewed example');requireValue(['product-documentation','interactive-example','documented-example'].includes(e.kind),'Invalid example kind');if(e.image){requireValue(/^\.\/assets\/examples\/[a-z-]+\.png$/.test(e.image.path),'Unsafe image path');https(e.image.sourceUrl);const asset=fs.readFileSync(path.join(directory,e.image.path));requireValue(asset.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'Invalid PNG');requireValue(crypto.createHash('sha256').update(asset).digest('hex')===e.image.sha256,'Image hash mismatch: '+e.id);requireValue(e.verification.renderCaptured,'Image without capture evidence');}else requireValue(!e.verification.renderCaptured,'Capture marked without an image');}
const output='// Generated by scripts/build-catalog.mjs. Edit catalog.json.\nwindow.PARTS_CATALOG = '+JSON.stringify(data,null,2).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029')+';\n';
const target=path.join(directory,'data/catalog.js');
if(process.argv.includes('--check'))requireValue(fs.existsSync(target)&&fs.readFileSync(target,'utf8')===output,'Generated catalog.js is stale');else fs.writeFileSync(target,output);
console.log(`Catalog valid: ${data.parts.length} parts, ${data.examples.length} official examples, ${data.examples.filter(e=>e.image).length} source captures.`);
